default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  host: localhost
  database: furima_39501_development


test:
  <<: *default
  database: furima_39501_test


production:
  <<: *default
  database: furima_39501_production
  username: furima_39501
  password: <%= ENV["FURIMA_39501_DATABASE_PASSWORD"] %>

